---
title: "BibliographieL2B"
---
Cette bibliographie sera progressivement complétée.

## Quelques outils

On fréquentera le *Dictionnaire d’éthique et de philosophie morale* dirigé par Monique Canto-Sperber. Il est au CDI.

Un site comprenant de nombreux articles concernant la morale: [*L'Encyclopédie philosophique*](https://encyclo-philo.fr/)

## En guise d'introduction

Monique Canto-Sperber et Ruwen Ogien, *La Philosophie morale*, Que sais-je ? Il est en ligne sur Cairn (Bordeaux Montaigne).

Dans les *Notions de philosophie* (Folio essais, Gallimard, 1995), on peut lire dans le tome II, "L'action" de Vincent Descombes, dans le tome III "Étique et morale" de Laurent Jaffro et "Le mal" de Francis Wolff.

## Aristote

Aristote, *Éthique à Nicomaque*, traduction Bodéüs, GF. On peut lui préférer la traduction de Jean Tricot, elle aussi accessible au format de poche chez Vrin.

On signale pour information le grand commentaire de René-Antoine Gauthier et de Jean-Yves Jolif, *L’Ethique à Nicomaque,  introduction, traduction et commentaire*, 4 vol., 1970. Voici une présentation générale de l’éthique aristotélicienne : R.-A. Gauthier, *La morale d’Aristote*, PUF, 1973. Beaucoup de textes pertinents dans le livre II de la *Rhétorique*.

## Autres références de philosophie ancienne

*Les Cyniques grecs*, choix, traduction, introduction et notes par Léonce Paquet, avant-propos de Marie-Odile Goulet-Cazé, Le Livre de poche, 1992

Carlos Lévy, *Les Philosophies héllénistiques*, Le Livre de poche, 1997. Il y est question du scepticisme, de l'épicurisme, du stoïcisme, de la Nouvelle Académie et du néopyrrhonisme. On repère aisément les pages concernant l'éthique.

Les textes des philosophes hellénistiques se lisent dans A.A. Long & D.N. Sedley, *Les Philosophies hellénistiques*, traduction par J. Brunschwig et P. Pellegrin, GF, 2001 (éd. anglaise 1987). Il y a trois tomes (I. Pyrrhon L'épicurisme II. Les Stoïciens III. Les Académiciens La renaissance du pyrrhonisme)

Le dernier cours de Michel Foucault au Collège de France est centré sur la philosophie ancienne, en particulier sur les Cyniques: *Le Courage de la vérité Le gouvernement de soi et des autres II Cours au Collège de rance 1984*, Gallimard Seuil, 2009.

## Spinoza

On peut aborder Spinoza en commençant par le petit livre de Gilles Deleuze, *Spinoza Philosophie pratique*, Les Editions de Minuit, 1981. On peut difficilement se lancer dans l’*Ethique* dans le peu de temps dont on dispose. Mais il est possible d’aborder ce livre par les scolies. Des regroupements thématiques des scolies sont proposés dans Deleuze, *Spinoza et le problème de l’expression*, Les Editions de Minuit, 1968 Appendice : Etude formelle du plan de l’Ethique et du rôle des scolies dans la réalisation de ce plan : les deux Ethiques. Cet appendice sera mis en ligne. Enfin un beau livre de Victor Delbos, *Le Problème moral dans la philosophie de Spinoza et dans l’histoire du spinozisme*. On peut consulter cet ouvrage en ligne,en cliquant [ici](https://archive.org/details/leproblmemorald00victgoog/page/XI/mode/1up?view=theater).

## Kant

Deux références fondamentales sont constituées par les *Fondements de la métaphysique des moeurs* (traduction Delbos, mais il y a une autre traduction, en GF, qui, elle, est d’Alain Renaut) et par la *Critique de la raison pratique* (traduction de Heinz Wismann et Luc Ferry en Folio, mais il en existe d’autres également en édition de poche).

Sur la philosophie pratique de Kant un ouvrage ancien: Victor Delbos, *La philosophie pratique de Kant*, PUF, 1926. Il est téléchargeable [ici](https://ia601307.us.archive.org/13/items/laphilosophiepra00delb/laphilosophiepra00delb.pdf)

## Hume

Hume, *Enquête sur les principes de la morale*, traduit par P. Baranger et P. Saltel, GF.

Sur un aspect très important de la pensée de Hume, un livre très court, très bien et très peu cher : Anne Auchatraire, *Traité de la nature humaine, II, III, 1 “de la liberté et de la nécessité”*, Ellipses, 2002

## Hegel

Hegel, *Principes de la philosophie du droit*, traduction de J.-F. Kervégan, PUF. Prendre une édition récente à cause de l'ajout de la traduction des additions. Vous pourriez en lire la seconde partie (Die Moralität) et les §§ 142 à 157 de la troisième (Die Sittlichkeit).

Les références à la *Phénoménologie de l'esprit* seront données ultérieurement.

Un bon article sur la philosophie de l’action de Hegel: Robert Pippin, « La théorie hégélienne de l'agentivité le problème de l'intérieur et de l'extérieur », *Philosophie*, 2008/4 n° 99. Disponible sur Cairn. ("Agentivité" est une assez vilaine traduction d'"agency".) Ces questions seront longuement développées.

Vous pourriez lire quelques textes de Jean-François Kervégan. Dans *L’Effectif et le rationnel Hegel et l’esprit objectif*, vous seraient très utiles le chapitre X, “La vérité de la moralité” et le chapitre XII “Sujets, normes et institutions. Qu’est-ce qu’une vie éthique ?” Les textes seront mis en ligne.

## Nietzsche

Nietzsche, *Éléments pour la généalogie de la morale Écrit de combat*, introduction, traduction et notes de Patrick Wotling, Le Livre de poche, 2000. Justification de la retraduction du titre aux pages 313-314 de cette édition.


Signalons un article de Michel Foucault, “Nietzsche, la généalogie, l’histoire” paru en 1971. On peut le trouver dans *Lectures de Nietzsche*, sous la direction de Jean-François Balaudé et Patrick Wotling, Le Livre de poche. Dans ce recueil, on lira en priorité l'article de Patrick Wotling, "La morale sans métaphysique".

## Dewey

John Dewey, *Reconstruction en philosophie*, “chapitre VII Reconstruction dans l’éthique”, Folio (Reconstruction in Philosophy, première édition 1920). Il y a une bonne préface de Richard Rorty. Le texte anglais est disponible [ici](https://archive.org/details/reconstructionin00deweuoft).

On peut lire également de Dewey, *La Quête de certitude Une étude de la relation entre connaissance et action*, “chapitre X La construction du bien”. Le texte sera mis à votre disposition grâce à la liste de diffusion.

## Divers

Vincent Descombes, *Le Complément de sujet Enquête sur le fait d’agir de soi-même*,Gallimard, 2004. On lira II. Eclaircissement logiques et syntaxiques et IV. Les éthiques du sujet. Du même auteur, on lira aussi dans *Le Raisonnement de l’ours et autres essais de philosophie pratique*, Seuil, 2007, les chapitres suivants : Introduction. Philosopher en matière pratique, Le raisonnement de l’ours, Que peut-on demander à la philosophie morale ?

Ruwen Ogien, *L’Ethique aujourd’hui : maximalistes et minimalistes*, Folio, 2007

John Langshaw Austin, “Plaidoyer pour les excuses”, dans *Ecrits philosophiques*, Seuil, 1994. Le texte sera mis à votre disposition grâce à la liste de diffusion. Le texte anglais est disponible [ici](http://spiritual-minds.com/philosophy/assorted/Austin,%20John%20-%20Philosophical%20Papers%202ed%20-%20Philosophy%20of%20Language.pdf) à la page 175.

Bérengère Parmentier, *Le Siècle des moralistes*, Points, Seuil, 2000. On peut fréquenter les *Maximes* de La Rochefoucauld. Dans Montaigne, on pourra lire au moins dans le troisième livre des *Essais*, le chapitre 10 “De mesnager sa volonté”. On ne négligera pas Pascal.

Pourquoi pas Paul Ricœur, *Du texte à l’action, Essais d’herméneutique II*, “La raison pratique”, p. 263-288, Points Seuil, 1986? Un petit texte qui peut être utile du fait de quelques remarques sur la rationalité pratique chez Aristote, Kant et Hegel.

Françoise Coblence, *Le Dandysme, obligation d'incertitude*, PUF, 1988. Disponible sur Cairn.
